# Generated by Django 3.0.2 on 2020-11-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('parentId', models.IntegerField(verbose_name='父Id')),
                ('synonym_describe', models.CharField(max_length=255, null=True, verbose_name='近义词')),
                ('level', models.IntegerField(verbose_name='层级')),
                ('url', models.CharField(max_length=255, null=True)),
                ('url_type', models.IntegerField(choices=[(0, '无类型'), (1, '数据接口'), (2, '产业链截图'), (3, 'dtApp截图'), (4, 'gif动图')], default=0)),
                ('status', models.IntegerField(choices=[(0, '失效'), (1, '可用')], default=1, verbose_name='可用状态')),
                ('chart_type', models.CharField(blank=True, default='', max_length=25, verbose_name='图表类型')),
            ],
            options={
                'verbose_name': '魔方菜单',
                'verbose_name_plural': '魔方菜单',
            },
        ),
        migrations.CreateModel(
            name='DataapiConfigmenuBp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('synonym_describe', models.CharField(blank=True, max_length=255, null=True)),
                ('parentid', models.IntegerField(db_column='parentId')),
                ('level', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('url_type', models.IntegerField(blank=True, null=True)),
                ('chart_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dataapi_configmenu_bp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DtechartsConfigMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('synonym_describe', models.CharField(blank=True, max_length=255, null=True)),
                ('parentid', models.IntegerField(db_column='parentId')),
                ('level', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('url_type', models.IntegerField(blank=True, null=True)),
                ('chart_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dtecharts_config_menu',
                'managed': True,
            },
        ),
    ]
