# Generated by Django 3.0.2 on 2020-11-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_est', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configmenu',
            table='dataapi_configmenu',
        ),
    ]
